shell = "zsh"

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[plugins.fzf-tab]
github = "Aloxaf/fzf-tab"

[plugins.zsh-abbr]
github = "olets/zsh-abbr"

# ohmyzsh git plugin (fish plugin-git equivalent, alias-based)
[plugins.ohmyzsh-git]
github = "ohmyzsh/ohmyzsh"
dir = "plugins/git"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
apply = ["defer"]

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
dir = "src"
apply = ["fpath"]
